## Data Transformation, cut, qcut, any, all, abs, sign, take, sample, get_dummies_Theory

---

* **`pd.cut(x, bins, right=True, labels=None, include_lowest=False, precision=3, duplicates='raise')`** – **kəsilmə (bölgü)** əməliyyatı apararaq `x` massivini və ya Series-ni **müəyyən intervallara bölür** və nəticə olaraq **hansı intervala düşdüyünü göstərən obyekt** qaytarır.

- `x` – bölünəcək **sayısal Series və ya array**,
- `bins` – interval sayı (tam ədəd) və ya **interval sərhədləri (siyahı kimi)**,
- `right=True` – intervalların **sağ sərhədi daxil edilir**,
- `labels=None` – intervallara **adlar (etiketlər)** verilir, `False` olsa etiketlər qaytarılmır,
- `include_lowest=False` – ilk intervalın **sol sərhədi də daxil edilsin**,
- `precision=3` – interval sərhədlərinin **ondalıq dəqiqliyi**,
- `duplicates='raise'` – sərhədlərdə təkrarlanma olsa, **xəta verir**, `drop` olsa təkrarlananları atır.

---

* **`pd.qcut(x, q, labels=None, retbins=False, precision=3, duplicates='raise')`** – `x` massivini və ya Series-ni **kvantilərə (bərabər sayda elementə malik intervallara)** bölür və hər elementin hansı kvantilə düşdüyünü göstərir.

- `x` – bölünəcək sayısal Series və ya array,
- `q` – kvantil sayı (məsələn, `4` – kvartillər) və ya kvantil sərhədlərinin siyahısı (məsələn, `[0, 0.25, 0.5, 0.75, 1]`),
- `labels=None` – intervallara veriləcək adlar, defaultda interval ifadələri olur,
- `retbins=False` – `True` olarsa, həm kvantil intervalları həm də sərhədlər qaytarılır,
- `precision=3` – sərhədlərin ondalıq dəqiqliyi,
- `duplicates='raise'` – təkrarlanan sərhədlər varsa xəta verir, `drop` olsa atır.


---

* **`df.any(axis=0, bool_only=None, skipna=True, level=None, **kwargs)`** – `df` adlı DataFrame-dəki **sətir və ya sütunlarda ən az bir `True` (və ya qeyri-sıfır) dəyərin** olub-olmadığını yoxlayır.

- `axis=0` – **hər sütun üzrə** yoxlayır, `axis=1` – **hər sətir üzrə**,
- `bool_only=None` – yalnız məntiqi (`bool`) tiplərlə işləsin,
- `skipna=True` – `NaN` dəyərləri **nəzərə almadan** hesablama aparır,
- `level=None` – çoxsəviyyəli indekslərdə istifadə olunur.

---

* **`df.all(axis=0, bool_only=None, skipna=True, level=None, **kwargs)`** – `df` adlı DataFrame-dəki **bütün sətir və ya sütunların bütün dəyərlərinin `True` (və ya qeyri-sıfır) olub-olmadığını** yoxlayır.

- `axis=0` – **hər sütun üzrə** yoxlayır, `axis=1` – **hər sətir üzrə**,
- `bool_only=None` – yalnız məntiqi (`bool`) tiplərlə işləsin,
- `skipna=True` – `NaN` dəyərləri **nəzərə almadan** hesablama aparır,
- `level=None` – çoxsəviyyəli indekslərdə istifadə olunur.

---

* **`np.sign(x)`** – NumPy funksiyası, `x`-dəki hər bir elementin işarəsini müəyyən edir və aşağıdakı dəyərləri qaytarır:

- `1` – element müsbətdirsə,
- `0` – element sıfırdırsa,
- `-1` – element mənfidirsə.

`x` skaler, vektor və ya massiv ola bilər, nəticə eyni ölçüdə massiv olur.


---

* **`df.take(indices, axis=0, inplace=False, ignore_index=False, errors='raise')`** – `df` DataFrame-dən **göstərilən indekslərə əsasən sətir və ya sütunları seçir**.

- `indices` – seçiləcək **sətir və ya sütun indekslərinin siyahısı və ya array-i** (pozitiv və ya mənfi tam ədədlər),
- `axis=0` – `0` sətir üzrə seçir, `1` sütun üzrə seçir,
- `inplace=False` – orijinal DataFrame dəyişmir, yeni DataFrame qaytarılır,
- `ignore_index=False` – `True` olarsa, nəticədə indeks sıfırdan başlayaraq yenidən qurulur,
- `errors='raise'` – indeks səhv olarsa xəta verir, `'ignore'` olsa gözardı edir.

---

* **`df.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)`** – `df` DataFrame-dən **təsadüfi sətir və ya sütunlar seçir**.

- `axis=None` – `0` (sətir) və ya `1` (sütun) üzrə seçim.
- `n=None` – seçiləcək **elementlərin sayı** (sətir və ya sütun sayı),
- `frac=None` – seçiləcək **faiz (kəsr)**, məsələn `0.1` (10%),
- `replace=False` – seçilən elementlər **təkrarlana bilər** (`True`) və ya təkrarlanmaz (`False`),
- `weights=None` – seçim üçün **çəki vektorları**,
- `random_state=None` – təsadüfi seçim üçün **seed** (təkrar təyin edilə bilər),

Əgər `n` və `frac` birlikdə verilsə, `n` üstünlük qazanır.

---

* **`pd.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, drop_first=False, dtype=None)`** – **Kateqoriyalı dəyişənləri (sütunları) one-hot encoding** formatına çevirir, yəni hər unikal dəyər üçün ayrıca sütun yaradır və orada 0/1 göstərir.

- `data` – **Series, DataFrame və ya array** tipində giriş məlumatı,
- `prefix=None` – yaranan sütun adları üçün **önlük (prefix)**,
- `prefix_sep='_'` – önlük ilə dəyər arasındakı **ayırıcı**,
- `dummy_na=False` – `True` olsa, NaN dəyərlər üçün ayrıca sütun yaradılır,
- `columns=None` – yalnız müəyyən **sütunları** çevirmək üçün siyahı,
- `drop_first=False` – `True` olarsa, ilk dummy sütun silinir (multikollearlığı azaltmaq üçün),
- `dtype=None` – yaranan sütunların **tipi** (məsələn, `int`, `float`).

### Nümunə

In [44]:
np.random.seed(3)
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

          0         1         2         3
0  1.788628  0.436510  0.096497 -1.863493
1 -0.277388 -0.354759 -0.082741 -0.627001
2 -0.043818 -0.477218 -1.313865  0.884622
3  0.881318  1.709573  0.050034 -0.404677
4 -0.545360 -1.546477  0.982367 -1.101068

In [45]:
data[np.all(data>0, axis=1)].head(5)

            0         1         2         3
61   1.103922  1.881755  0.593588  2.070879
68   1.619238  0.513093  0.695484  0.080457
80   2.019651  0.326262  0.861358  0.919008
88   0.138015  0.939503  0.127309  0.235027
101  0.236406  0.815604  1.860812  0.255590

In [46]:
data[(data>0).all(axis=1)].head(5)

            0         1         2         3
61   1.103922  1.881755  0.593588  2.070879
68   1.619238  0.513093  0.695484  0.080457
80   2.019651  0.326262  0.861358  0.919008
88   0.138015  0.939503  0.127309  0.235027
101  0.236406  0.815604  1.860812  0.255590

In [47]:
data[np.any(data>0, axis=1)].head(5)

          0         1         2         3
0  1.788628  0.436510  0.096497 -1.863493
2 -0.043818 -0.477218 -1.313865  0.884622
3  0.881318  1.709573  0.050034 -0.404677
4 -0.545360 -1.546477  0.982367 -1.101068
5 -1.185047 -0.205650  1.486148  0.236716

In [48]:
data[(data>0).any(axis=1)].head(5)

          0         1         2         3
0  1.788628  0.436510  0.096497 -1.863493
2 -0.043818 -0.477218 -1.313865  0.884622
3  0.881318  1.709573  0.050034 -0.404677
4 -0.545360 -1.546477  0.982367 -1.101068
5 -1.185047 -0.205650  1.486148  0.236716